import * as fs from "fs";
import * as path from "path";
import matter from "gray-matter";
import { atomicWrite } from "./fileWriter";
import { parseTaskBody } from "@shared/taskBodyParser";
import type { TaskInfo, MilestoneInfo } from "@shared/types";

export interface DecisionContent {
  id: string;
  title: string;
  body: string;
}

/**
 * Read a decision file and return its content for embedding in CONTEXT.md.
 * Returns null (with a warning comment) if the file cannot be found.
 */
async function readDecisionContent(
  workspacePath: string,
  decisionId: string,
): Promise<DecisionContent> {
  const decisionDir = path.join(workspacePath, ".decisions");
  try {
    const entries = await fs.promises.readdir(decisionDir);
    const match = entries.find(
      (e) => e.startsWith(decisionId) && e.endsWith(".md"),
    );
    if (!match) {
      return {
        id: decisionId,
        title: decisionId,
        body: `> Note: Decision file not found for ${decisionId}.`,
      };
    }
    const filePath = path.join(decisionDir, match);
    const raw = await fs.promises.readFile(filePath, "utf-8");
    const { data, content } = matter(raw);
    const title = typeof data.title === "string" ? data.title : decisionId;
    return { id: decisionId, title, body: content.trim() };
  } catch {
    return {
      id: decisionId,
      title: decisionId,
      body: `> Note: Decision file not found for ${decisionId}.`,
    };
  }
}

/**
 * Generate CONTEXT.md inside the worktree root.
 *
 * The file is written atomically and intentionally ephemeral —
 * it will be regenerated if the worktree is recreated.
 */
export async function generateContextFile(
  worktreePath: string,
  task: TaskInfo,
  taskBody: string,
  workspacePath: string,
): Promise<void> {
  const parsed = parseTaskBody(taskBody);
  const isoDate =
    new Date().toISOString().replace("T", " ").slice(0, 19) + " UTC";

  // Read linked decision files
  const decisions: DecisionContent[] = [];
  for (const decId of task.decisions) {
    decisions.push(await readDecisionContent(workspacePath, decId));
  }

  // Read linked milestone
  let milestone: MilestoneInfo | null = null;
  if (task.milestone) {
    milestone = await readMilestoneInfo(workspacePath, task.milestone);
  }

  const lines: string[] = [];

  // Header
  lines.push(`# Task Context: ${task.title}`);
  lines.push("");
  lines.push(
    `> Generated by Grove on ${isoDate}. Do not edit — regenerated on each worktree creation.`,
  );
  lines.push("");

  // Task metadata
  lines.push("## Task");
  lines.push("");
  lines.push(`**ID:** ${task.id}`);
  lines.push(`**Branch:** ${task.branch ?? "(not set)"}`);
  lines.push(`**Priority:** ${task.priority ?? "not set"}`);
  lines.push(`**Agent:** ${task.agent ?? "not set"}`);
  lines.push("");

  // Description
  lines.push("## Description");
  lines.push("");
  lines.push(parsed.description || "(no description provided)");
  lines.push("");

  // Definition of Done
  lines.push("## Definition of Done");
  lines.push("");
  if (parsed.dod.length > 0) {
    for (const item of parsed.dod) {
      lines.push(`- [${item.checked ? "x" : " "}] ${item.text}`);
    }
  } else {
    lines.push("(no checklist items)");
  }
  lines.push("");

  // Context for agent
  lines.push("## Context for Agent");
  lines.push("");
  lines.push(parsed.contextForAgent || "(no context provided)");
  lines.push("");

  // Milestone (optional)
  if (milestone) {
    lines.push(`## Milestone: ${milestone.title}`);
    lines.push("");
    lines.push(`**ID:** ${milestone.id}`);
    lines.push("");
    if (milestone.description) {
      lines.push(milestone.description);
      lines.push("");
    }
  }

  // Linked decisions (optional)
  if (decisions.length > 0) {
    lines.push("## Linked Decisions");
    lines.push("");
    for (const dec of decisions) {
      lines.push(`### ${dec.id}: ${dec.title}`);
      lines.push("");
      lines.push(dec.body);
      lines.push("");
      lines.push("---");
      lines.push("");
    }
  }

  const content = lines.join("\n");
  await atomicWrite(path.join(worktreePath, "CONTEXT.md"), content);
}

/**
 * Read milestone info for embedding in CONTEXT.md.
 */
async function readMilestoneInfo(
  workspacePath: string,
  milestoneId: string,
): Promise<MilestoneInfo | null> {
  const milestoneDir = path.join(workspacePath, ".milestones");
  try {
    const entries = await fs.promises.readdir(milestoneDir);
    const match = entries.find(
      (e) => e.startsWith(milestoneId) && e.endsWith(".md"),
    );
    if (!match) return null;
    const filePath = path.join(milestoneDir, match);
    const raw = await fs.promises.readFile(filePath, "utf-8");
    const { data, content } = matter(raw);
    return {
      id: milestoneId,
      title: typeof data.title === "string" ? data.title : milestoneId,
      status: data.status === "closed" ? "closed" : "open",
      created: typeof data.created === "string" ? data.created : null,
      tags: Array.isArray(data.tags) ? data.tags.map(String) : [],
      description: content.trim(),
      filePath,
      taskCounts: { total: 0, done: 0, doing: 0, review: 0, backlog: 0 },
    };
  } catch {
    return null;
  }
}
